### ISSUE TITLE
Stochastik: Fehler in Transformations Formel

### ISSUE THREAD

**Issue by TobiasMeierdierks** [pblan/matse-spicker#64]
"Algorithmus: Transformation auf standardisierte Variable" (S.24)

Der Punkt "P(a <= X <= b) = Phi((a-u)/s) - Phi((b-u)/s)" sollte laut Folien umgekehrt "P(a <= X <= b) = Phi((b-u)/s) - Phi((a-u)/s)" lauten, sonst erhält man eine negative Wahrscheinlichkeit.

**Comment by pblan** [comment]
@TobiasMeierdierks komplett korrekt. Werde die Änderung schon mal im Repo einpflegen, die PDF werde ich dann auch updaten.
